### ISSUE TITLE
Color picker compatibility with external script

### ISSUE THREAD

**Issue by sbarrack** [toobeeh/skribbltypo#1]
[The addition of the color picker](https://github.com/sbarrack/skribbltypo/compare/master...sbarrack:e7acb87972f9319bfb3e96a5b0b31b8a8825dd56) breaks some features of the [community script](https://github.com/sbarrack/skribbl-community-scripts). Will isolate the discrepancies and submit a pull request down the line once that is patched.

**Comment by toobeeh** [comment]
Fyi, i'll release a code rework some day this week - it completely changes where the code is located.
If your fix is made outside of the picker.js, i'd recommend waiting for my commit to avoid a merge conflict.
