### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by tw0f1sh** [toobeeh/skribbltypo#32]
I use Firefox and after i use "toggle lobby filter" to search lobbys after my friends name, i get the msgbox "Connection lost." after 1-4 sec. (plugin searched some lobbys befor this happens).

is there some option to turn down the refresh speed?

Thanks.

**Comment by toobeeh** [comment]
Hi, there is no option available to set within typo.
You can clone the repo and set another timeout here: https://github.com/toobeeh/skribbltypo/blob/oldSkribbl/features/genericFunctions.js#L232

To use this modified version in firefox, you would have to sign your version. 
It's easier in chrome where you can just select a manifest file.
