### ISSUE TITLE
Palette broken

### ISSUE THREAD

**Issue by Gremious** [toobeeh/skribbltypo#33]
With the new skribble update, when the "Original Palette" option is on, half the colors are missing (very notably - black).

When the other palette options are turned on, other people will not actually see you draw anything, even if you use an existing color (easily repro by opening the game in two browsers in a private room).

**Comment by toobeeh** [comment]
Can you try this palette? When I tested, i was able to view it in a non-typo game:
`{"rowCount":13,"name":"Original Fix","colors":[{"color":"#ffffff"},{"color":"#c1c1c1"},{"color":"#ef130b"},{"color":"#ff7100"},{"color":"#ffe400"},{"color":"#00cc00"},{"color":"#00ff91"},{"color":"#00b2ff"},{"color":"#231fd3"},{"color":"#a300ba"},{"color":"#df69a7"},{"color":"#ffac8e"},{"color":"#a0522d"},{"color":"#000000"},{"color":"#505050"},{"color":"#740b07"},{"color":"#c23800"},{"color":"#e8a200"},{"color":"#004619"},{"color":"#00785d"},{"color":"#00569e"},{"color":"#0e0865"},{"color":"#550069"},{"color":"#873554"},{"color":"#cc774d"},{"color":"#63300d"}]}`

Other than that, a fix is on the way as mentioned.
