### ISSUE TITLE
Match filter finds a game, but then kicks you out back to the main page immedatelly.

### ISSUE THREAD

**Issue by Gremious** [toobeeh/skribbltypo#34]
Adding a filter and searching works fine, but after a game is found, it kicks you back out into the main menu, rendering the match-finder nonfunctional.

**Comment by toobeeh** [comment]
Thanks for the issue.
This and issue #32 are aleady fixed in the latest version, donwload the repo and load it as extension to check it.
Unfortunately the update is stuck in the chrome store for a few days, but it will eventually release this week.
Firefox has the new version too.
